;/*FB_PKG_DELIM*/

__d("ApproveFromAnotherDeviceRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="25383236244605976"}),null);
__d("BaseMultiPageEntryPointImpl.react",["CometPlaceholder.react","CometRelay","clearTimeout","react","setTimeout"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=e,c=u.useEffect,d=u.useRef;function m(e){var t=e.entryPoint,n=e.environmentProvider,a=e.fallback,i=e.loadedEntryPoint,l=e.otherProps,u=e.placeholderComponent,m=u===void 0?r("CometPlaceholder.react"):u,p=e.preloadParams,_=e.usePlaceholder,f=_===void 0?!0:_,g=o("CometRelay").useEntryPointLoader(n,t),h=g[0],y=g[1],C=g[2],b=h!=null?h:i,v=d(null);c(function(){return v.current!=null&&(r("clearTimeout")(v.current),v.current=null),b.isDisposed&&y(p),function(){v.current=r("setTimeout")(function(){h?C():i.dispose(),v.current=null},6e4)}},[C,b.isDisposed,i,p,y,h]);var S=s.jsx(o("CometRelay").EntryPointContainer,{entryPointReference:b,props:l});return f?s.jsx(m,{fallback:a,children:S}):S}m.displayName=m.name+" [from "+i.id+"]",l.default=m}),98);
__d("PolarisFriendingConfirmationDialogQuery_instagramRelayOperation",[],(function(t,n,r,o,a,i){a.exports="9596244033796883"}),null);
__d("PolarisIGCoreAvatar.react",["cx","PolarisFastLink.react","PolarisIGCoreConstants","joinClasses","react","react-compiler-runtime"],(function(t,n,r,o,a,i,l,s){"use strict";var e,u=e||(e=o("react"));function c(e){var t=e.children,n=e.className,o=e.href,a=e.onClick;switch(!0){case o!=null:return u.jsx(r("PolarisFastLink.react"),{className:n!=null?n:void 0,href:o,onClick:a,children:t});case a!=null:return u.jsx("button",{className:r("joinClasses")(n,"_aag4"),onClick:a,children:t});default:return u.jsx("span",{className:n,children:t})}}c.displayName=c.name+" [from "+i.id+"]";function d(e){var t=o("react-compiler-runtime").c(11),n=e.alt,a=e.dangerouslySetClassName,i=e.href,l=e.onClick,s=e.size,d=e.src,m=s===void 0?"medium":s,p=a!=null?a.__className:null,_;t[0]===Symbol.for("react.memo_cache_sentinel")?(_={className:"x1c9tyrk xeusxvb x1pahc9y x1ertn4p x972fbf x10w94by x1qhh985 x14e42zd xln7xf2 xk390pu xdj266r x14z9mp xat24cr x1lziwak xexx8yu xyri2b x18d9i69 x1c1uobl x11njtxf"},t[0]=_):_=t[0];var f=r("PolarisIGCoreConstants").AVATAR_SIZES[m],g=r("PolarisIGCoreConstants").AVATAR_SIZES[m],h;t[1]!==n||t[2]!==d||t[3]!==f||t[4]!==g?(h=u.jsx("img",babelHelpers.extends({alt:n},_,{height:f,src:d,width:g})),t[1]=n,t[2]=d,t[3]=f,t[4]=g,t[5]=h):h=t[5];var y;return t[6]!==p||t[7]!==i||t[8]!==l||t[9]!==h?(y=u.jsx(c,{className:p,href:i,onClick:l,children:h}),t[6]=p,t[7]=i,t[8]=l,t[9]=h,t[10]=y):y=t[10],y}l.default=d}),98);
__d("XPolarisEditBoostedAdControllerRouteBuilder",["jsRouteBuilder"],(function(t,n,r,o,a,i,l){var e=r("jsRouteBuilder")("/b/edit_boosted_ad/",Object.freeze({context:"ads_manager_edit_promote_unknown"}),void 0),s=e;l.default=s}),98);
__d("XPolarisPostControllerRouteBuilder",["jsRouteBuilder"],(function(t,n,r,o,a,i,l){var e=r("jsRouteBuilder")("/{permalink_key}/{shortcode}/{?slug}/",Object.freeze({chaining:!1,viewer:!1,show_insights:!1}),void 0),s=e;l.default=s}),98);
__d("usePageEntryPointPrerenderer",["FBLogger","react","useCometEntryPointPrerendererWithQueryTimeoutPrivate"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.useCallback,c=s.useState;function d(e,t,n){var o=c(),a=o[0],i=o[1],l=r("useCometEntryPointPrerendererWithQueryTimeoutPrivate")(e,t,n),s=l[0],d=l[1],m=u(function(e){var t=s();if(i(t),t==null){r("FBLogger")("comet_ui").blameToPreviousFrame().mustfix("Unable to present comet page EntryPoint component, preloadParams not set");return}t!=null&&e(t)},[s]);return[m,d,a]}l.default=d}),98);
__d("usePushPage",["BaseMultiPageEntryPointImpl.react","BaseMultiPageViewContext","FBLogger","react","useCometRelayEntrypointContextualEnvironmentProvider","usePageEntryPointPrerenderer"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=e,c=u.useCallback,d=u.useContext;function m(e,t,n){n===void 0&&(n="button");var o=r("useCometRelayEntrypointContextualEnvironmentProvider")(),a=d(r("BaseMultiPageViewContext")),i=r("usePageEntryPointPrerenderer")(e,t,n),l=i[0],u=i[1],m=c(function(n,i){var u=i===void 0?{}:i,c=u.fallback,d=u.pageKey;if(a==null)throw r("FBLogger")("BaseMultiPageView").blameToPreviousFrame().mustfixThrow("usePushPage can only be used inside BaseMultiPageView.");t!=null&&l(function(i){return a.pushPage(function(){return s.jsx(r("BaseMultiPageEntryPointImpl.react"),{entryPoint:e,environmentProvider:o,fallback:c!=null?c:a.fallback,loadedEntryPoint:i,otherProps:n,placeholderComponent:a.placeholderComponent,preloadParams:t})},{pageKey:d})})},[a,o,l,e,t]);return[m,u]}l.default=m}),98);